### ISSUE TITLE
Terminated by signal SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by amacgregorhumi** [kamek-pf/ntfd#7] opened 2021-04-07 11:32 UTC
Running into the following issue: 

```
❯ ntfd
The following modules were ignored: 
 - mpd (Disabled)

Started OpenWeatherMap synchronization service.
Started Github synchronization service.
fish: “ntfd” terminated by signal SIGSEGV (Address boundary error)
```

from syslog: 

```
Apr  7 07:31:00 EventHorizon01 systemd[1]: systemd-localed.service: Succeeded.
Apr  7 07:31:07 EventHorizon01 kernel: [423164.998337] ntfd:w[2051913]: segfault at 0 ip 0000000000000000 sp 00007fddc64af888 error 14 in ntfd[400000+1000]
Apr  7 07:31:07 EventHorizon01 kernel: [423164.998345] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
```

**Comment by kamek-pf** [comment] 2021-04-07 18:18
Interesting, I never ran into this one before.
Did you compile from source or are you using the static binary ?

Also, what distro and what kernel version are you using ?

**Comment by kamek-pf** [comment] 2021-11-15 23:30
No further details here, closing as I can't reproduce.

**Closed by kamek-pf** 2021-11-15 23:30 UTC
